# Generated by Django 3.2 on 2021-04-15 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Survived', models.CharField(max_length=10)),
                ('Passenger_Class', models.CharField(default='Third', max_length=10)),
                ('Sex', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Fare_Paid', models.IntegerField(default=0)),
                ('Embarked', models.CharField(max_length=10)),
                ('Size_of_Group', models.IntegerField()),
                ('Cabin_Class', models.CharField(default=0, max_length=1)),
                ('Title', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
